export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_ITEMS = 'FETCH_MENU_ITEMS';
export const MENU_FETCH_REQUEST = 'MENU_FETCH_REQUEST';
export const MENU_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS';
export const MENU_FETCH_FAILURE = 'MENU_FETCH_FAILURE';

export const FETCH_PAGE = 'FETCH_PAGE';
export const PAGE_FETCH_REQUEST = 'PAGE_FETCH_REQUEST';
export const PAGE_FETCH_SUCCESS = 'PAGE_FETCH_SUCCESS';
export const PAGE_FETCH_FAILURE = 'PAGE_FETCH_FAILURE';
