export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const RECEIVE_POKEMON = 'RECEIVE_POKEMON';

export const FETCH_DETAIL_REQUEST = 'FETCH_DETAIL_REQUEST';
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_FAILURE = 'FETCH_DETAIL_FAILURE';

export const ADD_TO_OWNED = 'ADD_TO_OWNED';
export const REMOVE_FROM_OWNED = 'REMOVE_FROM_OWNED';
